---
workflow:
  rules:
    - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == $CI_DEFAULT_BRANCH
      when: never
    - if: $CI_COMMIT_TAG
      when: never
    - when: always

stages:
  - merge-check
  - lint

git:
  stage: merge-check
  tags:
    - docker
  image:
    name: alpine/git:latest
    entrypoint: [""]
  script:
    - git show $CI_MERGE_REQUEST_TARGET_BRANCH_SHA > /dev/null 2>&1 || echo "Cannot find target branch commint in current branch. Probably rebase or merge required"
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
    - if: $CI_OPEN_MERGE_REQUESTS
      when: never

shellcheck:
  variables:
    CHANGES_FROM: $CI_COMMIT_SHA
    CHANGES_TO: $CI_COMMIT_BEFORE_SHA
  stage: lint
  tags:
    - docker
  image: koalaman/shellcheck-alpine:stable
  before_script:
    - apk add --no-cache git
  script:
    - >-
      shellcheck $(git -C "${CI_PROJECT_DIR}" diff-tree --diff-filter=dr --name-only -r "${CHANGES_FROM}" "${CHANGES_TO}" | grep \.sh)
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
      variables:
        CHANGES_TO: $CI_MERGE_REQUEST_DIFF_BASE_SHA
      changes:
        - "**/*.sh"
    - when: on_success
      changes:
        - "**/*.sh"
    - if: $CI_OPEN_MERGE_REQUESTS
      when: never
